### ISSUE TITLE
[Feature Request] Add option to throttle requests

### ISSUE THREAD

**Issue by thor-vath** [Gilks/enumerid#2] opened 2018-07-10 15:51 UTC
Please add a flag to throttle the rate at which the enumeration occurs.

**Comment by Gilks** [comment] 2018-07-10 20:08
This should be a pretty easy thing to implement. I'll knock this out soon!

**Comment by Gilks** [comment] 2018-07-13 14:58
I've added a new dev branch. I don't have easy access to a DC right now- can you try out the new `-t` argument on the dev branch?

You should be able to specify a maximum thread count now. @Silburfuchs can probably help with the DC. If this works as intended, I'll get it merged into master.

https://github.com/Gilks/enumerid/tree/dev

**Comment by Script-Nomad** [comment] 2018-10-27 20:57
Tested this on a DC while on a recent pentest. Tested with 2 and 20 threads, and the running speeds were pretty much indistinguishable. I don't believe the speed at which RID cycles occur is going to be impacted by the number of threads but rather the rate the requests themselves are being sent. You may need to set a rate-limit flag that introduces a sleep between requests by number of milliseconds. Something akin to Nmap's Timing flags <T0, T1,T2,T3,T4,T5>

My guess is the current rate is going to be the fastest possible, so setting a default rate-limit at 50ms between requests seems reasonable so as not to overwhelm old DCs, and optionally set up to a 2000ms rate-limit for your "paranoid" mode. Sending x-number of requests per y-seconds in bursts could also be a possible solution. But I'm probably over-thinking it. xD

**Comment by Gilks** [comment] 2019-04-26 22:50
Closing due to inactivity.

**Closed as completed by Gilks** 2019-04-26 22:50 UTC
Labels: enhancement
